domain/urls.py
"""
    import needed things
"""
from django.urls import path
from domain.views import DashboardView, funct, CreateDomainView

app_name = "domain"
urlpatterns = [
    path("", funct, name="home"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("domain/add/", CreateDomainView.as_view(), name="add"),
]

page_speed_insights/urls.py
"""
    Import needed things
"""
from django.urls import path
from page_speed_insights.views import page_speed_scrap_url, report_data, \
    detail_report_data, flag_data, PageInsightAjaxDatatableView

app_name = "page_speed_insights"
urlpatterns = [
    path("report/", page_speed_scrap_url, name="report"),
    path("show_data/<int:pk>/", report_data, name="show_data"),
    path('api/page-insight/<int:pk>/', PageInsightAjaxDatatableView.as_view(), name="page_insight_list"),
    path("detail_data/<int:pk>/", detail_report_data, name="detail_data"),
    path("flag_data/<int:pk>/", flag_data, name="flag_data"),
]

scrapper/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("domain.urls")),
    path("user/", include("user.urls")),
    path("", include("page_speed_insights.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
"""
    import needed things
"""
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [path("register/", views.RegistrationView.as_view(), name="register"),
               path('login/', views.LoginView.as_view(), name='login'),
               path('logout/', views.LogoutView.as_view(), name='logout'),
               ]

domain/models.py
"""
      Import Models From Django db
"""
from django.db import models
from django.contrib.auth.models import User


class TimeStampModel(models.Model):
    """
          TimeStampModel For datetime
    """
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        """
             Meta For abstract
        """
        abstract = True


class Domain(TimeStampModel):
    """Domain table"""
    STATUS_CHOICES = (
        (0, "Fetching Url"),
        (1, "Fetching Page Speed Data"),
        (2, "Done"),
    )
    name = models.URLField()
    user = models.ForeignKey(User, related_name="domains",
                             on_delete=models.CASCADE)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES, default=0)

    def __str__(self):
        return str(self.name)


class DomainUrl(TimeStampModel):
    """
        DomainUrl is for storing data of domain name and url
    """
    domain = models.ForeignKey(Domain, on_delete=models.CASCADE)
    url = models.CharField(max_length=1024)

    class Meta:
        """
              Meta for unique_together
        """
        unique_together = ("domain", "url")

domain/forms.py
"""
    below urlparse for getting name
"""
from urllib.parse import urlparse
from django import forms
from domain.models import Domain


class DomainForm(forms.ModelForm):
    """
        Form Validation
    """
    class Meta:
        """
            Getting Model Details
        """
        model = Domain
        fields = ("name",)

        def __str__(self):
            return self.__class__.__name__

    def clean(self):
        """
            Clean Method For Form Submit
        """
        cleaned_data = super(DomainForm, self).clean()
        parsed_url = urlparse(cleaned_data.get('name'))
        cleaned_data['name'] = f"{parsed_url.scheme}://{parsed_url.netloc}"

domain/views.py
"""
    import needed things
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView
from django.contrib import messages
from domain.forms import DomainForm
from domain.models import Domain
from domain.tasks import scrapp_url_in_domain


class DashboardView(LoginRequiredMixin, ListView):
    """
        DashboardView
    """
    template_name = 'domain/dashboard.html'
    paginate_by = 10

    def get_queryset(self):
        """
            For getting get_context_data
        """
        return Domain.objects.filter(user=self.request.user).order_by('-created_at')


def funct(request):
    """
        funct for redirecting to dashboard
    """
    return redirect(reverse("domain:dashboard"))


class CreateDomainView(LoginRequiredMixin, CreateView):
    """
        CreateDomainView for creating Domain
    """
    template_name = "domain/create.html"
    form_class = DomainForm
    success_url = reverse_lazy("domain:dashboard")

    def form_valid(self, form):
        """
             Form validation
        """
        name = form.cleaned_data["name"]
        if self.request.user.domains.filter(name=name, status__in=[0,1]).exists():
            form.add_error("name", "Report generate is in progress.")
            return self.form_invalid(form)
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        scrapp_url_in_domain.delay(obj.id)
        messages.success(self.request, f"Report generating for {name} has been start!")
        return HttpResponseRedirect(self.success_url)

templates/domain/create.html
<!-- login.html -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block extra_header %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'domain:dashboard' %}">My Reports</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'domain:add' %}">Generate New Report</a>
    </li>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Add Domain</h5>
            <form method="POST" autocomplete="off">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Generate Report</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/domain/dashboard.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block extra_header %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'domain:dashboard' %}">My Reports</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'domain:add' %}">Generate New Report</a>
    </li>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Welcome, {{request.user}}</h5>
            {% include 'partial/alert-msg.html' %}
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Domain name</th>
                    <th scope="col">Report generate time</th>
                    <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
                {% for domain in object_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ domain.name }}</td>
                    <td>{{ domain.created_at }}</td>
                    <td>
                        {% if domain.status == 2 %}
                            <a class="btn btn-primary" href="{% url 'page_speed_insights:show_data' domain.id %}">View</a>
                        {% else %}
                            <button class="btn btn-primary" disabled>
                                <span class="spinner-border spinner-border-sm"></span> {{ domain.get_status_display }}
                            </button>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <!--Pagination-->
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                  </li>
                {% else %}
                    <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
                  </li>
                {% endif %}

                {% if page_obj.number|add:'-4' > 1 %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
                {% endif %}

                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item active" aria-current="page">
                      <span class="page-link">
                        {{ i }}
                        <span class="sr-only">(current)</span>
                      </span>
                    </li>
                    {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                         <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                   <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
                {% endif %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                  </li>
                {% else %}
                    <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
                  </li>
                {% endif %}
              </ul>
            </nav>
            <!--end of Pagination-->
        </div>
    </div>
{% endblock %}