domain/urls.py
"""
    import needed things
"""
from django.urls import path
from domain.views import DashboardView, funct, CreateDomainView

app_name = "domain"
urlpatterns = [
    path("", funct, name="home"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("domain/add/", CreateDomainView.as_view(), name="add"),
]

page_speed_insights/urls.py
"""
    Import needed things
"""
from django.urls import path
from page_speed_insights.views import page_speed_scrap_url, report_data, \
    detail_report_data, flag_data, PageInsightAjaxDatatableView

app_name = "page_speed_insights"
urlpatterns = [
    path("report/", page_speed_scrap_url, name="report"),
    path("show_data/<int:pk>/", report_data, name="show_data"),
    path('api/page-insight/<int:pk>/', PageInsightAjaxDatatableView.as_view(), name="page_insight_list"),
    path("detail_data/<int:pk>/", detail_report_data, name="detail_data"),
    path("flag_data/<int:pk>/", flag_data, name="flag_data"),
]

scrapper/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("domain.urls")),
    path("user/", include("user.urls")),
    path("", include("page_speed_insights.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
"""
    import needed things
"""
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [path("register/", views.RegistrationView.as_view(), name="register"),
               path('login/', views.LoginView.as_view(), name='login'),
               path('logout/', views.LogoutView.as_view(), name='logout'),
               ]

templates/pagespeed/report.html
{% extends 'base.html' %}
{% load data %}
{% load static %}


{% block extrastyle %}
    <link href="{% static 'style.css' %}" rel="stylesheet" />
    <link href="{% static 'ajax_datatable/css/style.css' %}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css">
{% endblock extrastyle %}

{% block extra_header %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'domain:dashboard' %}">My Reports</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'domain:add' %}">Generate New Report</a>
    </li>
{% endblock %}

{% block content %}
    {% if exists %}
    <label style="font-size:22px;"><b>If you want generate report after 3 days click here</b></label>
    <div class="custom-control custom-switch">
        <input type="checkbox" class="on_off" value="True" id="new_chat_message_received">
        <input type="hidden" value="{{New_chat_message.is_enable}}" id="new_chat_message_received_">
    </div>
    {% endif %}
    <table id="datatable_permissions">
    </table>
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" src="{% static 'ajax_datatable/js/utils.js' %}"></script>
    <script src="//cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>

<script>
   $(document).on("change", ".on_off", function () {
         if ($(this).is(':checked')) {
            var flag = "True"
          } else {
            var flag = "False"
          }
         var id = $(this).attr('id');
            $.ajax({
                url: "{% url 'page_speed_insights:flag_data'  domain.id %}",
                type: 'POST',
                headers: {"X-CSRFToken": "{{csrf_token}}"},
                data: {"id": id, "flag": flag},
                success: function (response) {
                },
            })
        });
    $(document).ready(function() {
        table = AjaxDatatableViewUtils.initialize_table(
            $('#datatable_permissions'),
            "{% url 'page_speed_insights:page_insight_list' domain.id %}",
            {
                // extra_options (example)
                processing: false,
                autoWidth: false,
                full_row_select: true,
                scrollX: false,
                details: false,
                full_row_select: false,
            },
        );
    });

</script>
{% endblock %}

templates/pagespeed/report_data.html
{% load data %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
html{
  font-size: 62.5%;
}

.posts-listing{
  display: flex;
  flex-wrap: wrap;
  max-width: 100%;
}

.post-item{
  width: calc(33.33% - 40px);
  margin: 20px;
  flex: 0 0 auto;
  font-family: "Lato", sans-serif;
  font-size: 1.6rem;
}

.post-item__inner{
  display: flex;
  flex-direction: column;
  height: 100%;
  border-radius: 4px;
  background-color: #F7F8F8;
  box-shadow: 0 5px 15px rgba(0,0,0,0.1);
  overflow: hidden;
  transition: box-shadow .2s;
  color: black;
  text-decoration: none;
}

.post-item__thumbnail-wrapper{
  width: 100%;
  height: 0;
  padding-bottom: 60%;
  flex: 0 0 auto;
  position: relative;
  clip-path: polygon(0 0, 100% 0, 100% 90%, 0 100%);
  overflow: hidden;
  transition: clip-path .2s;
}

.post-item__thumbnail{
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  background-size: cover;
  transition: transform .3s;
}

.post-item__thumbnail-wrapper:after{
  content: "";
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
  z-index: 1;
  background-image: linear-gradient(to top, rgba(136,27,132,0.2), rgba(162,77,211,0.03));
}

.post-item__content-wrapper{
  padding: 2rem;
  position: relative;
  height: auto;
  flex: 1 1 auto;
  display: flex;
  flex-direction: column;
}

.post-item__title{
  color: white;
  line-height: 1.6;
  margin-top: -4rem;
  font-size: 2.6rem;
  margin-bottom: 1rem;
}

.post-item__title span{
  display: inline;
  background-image: linear-gradient(to right, rgba(162,77,211), rgba(136,27,132));
  padding: .2rem .6rem;
  -webkit-box-decoration-break: clone;
  box-decoration-break: clone;
}

.post-item__metas{
  margin-bottom: 2rem;
}

.post-item__meta--date{
  color: #6d6d6d;
  letter-spacing: 0.01rem;
  font-size: 1.4rem;
}

.post-item__meta--category{
  display: inline-block;
  background-color: #a24dd3;
  color: white;
  font-size: 1.1rem;
  text-transform: uppercase;
  letter-spacing: 0.01rem;
  font-weight: 700;
  padding: 2px;
}

.post-item__excerpt{
  margin-bottom: 2rem;
}

.post-item__read-more-wrapper{
  margin-top: auto;
}

.post-item__read-more{
  padding: 3px 0;
  display: inline;
  background-image: linear-gradient(#a24dd3, #a24dd3);
  background-repeat: no-repeat;
  background-size: 100% 2px;
  background-position: left bottom;
  transition: background-size .3s;
}

/* hover state */

.post-item__inner:hover{
    box-shadow: 0 10px 20px rgba(0,0,0,0.3);
}

.post-item__inner:hover .post-item__thumbnail-wrapper{
  clip-path: polygon(0 0, 100% 0, 100% 100%, 0 100%);
}
.post-item__inner:hover .post-item__thumbnail{
  transform: scale(1.1);
}

.post-item__inner:hover .post-item__read-more{
  background-size: 30% 2px;
}
</style>
</head>
{% block content %}

<body>
<section class="posts-listing">

<article class="post-item">
  <a class="post-item__inner" href="#">
    <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          First Contentful Paint:-
          {{data.0.result.lighthouseResult.audits | first_contentful_paint}}</div>
    </div>

          <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          First Contentful Paint Details:-{{data.0.result.lighthouseResult.audits | first_contentful_paint_des}}</div>
    </div>

  </a>
</article>
    <article class="post-item">
  <a class="post-item__inner" href="#">
    <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Speed Index:-
          {{data.0.result.lighthouseResult.audits | speed_index}}</div>
    </div>

          <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Speed Index Details:-{{data.0.result.lighthouseResult.audits | speed_index_des}}</div>
    </div>

  </a>
</article>

    <article class="post-item">
  <a class="post-item__inner" href="#">
    <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Largest Contentful Paint:-
          {{data.0.result.lighthouseResult.audits | largest_contentful_paint}}</div>
    </div>

          <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Largest Contentful Paint Details:-{{data.0.result.lighthouseResult.audits | largest_contentful_paint_des}}</div>
    </div>

  </a>
</article>

        <article class="post-item">
  <a class="post-item__inner" href="#">
    <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Time to Interactive:-
          {{data.0.result.lighthouseResult.audits.interactive.displayValue}}</div>
    </div>

          <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Time to Interactive Details:-{{data.0.result.lighthouseResult.audits.interactive.description}}</div>
    </div>

  </a>
</article>
     <article class="post-item">
  <a class="post-item__inner" href="#">
    <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Total Blocking Time:-
          {{data.0.result.lighthouseResult.audits | total_blocking_time}}</div>
    </div>

          <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Total Blocking Time Details:-{{data.0.result.lighthouseResult.audits | total_blocking_time_des}}</div>
    </div>

  </a>
</article>

      <article class="post-item">
  <a class="post-item__inner" href="#">
    <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Cumulative Layout Shift:-
          {{data.0.result.lighthouseResult.audits | cumulative_layout_shift}}</div>
    </div>

          <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Cumulative Layout Shift Details:-{{data.0.result.lighthouseResult.audits | cumulative_layout_shift_des}}</div>
    </div>

  </a>
</article>

          <article class="post-item">
  <a class="post-item__inner" href="#">
    <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Server Response:-
          {{report.result.lighthouseResult.audits | server_response_time}}</div>
    </div>

          <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
           Server Response Details:-{{data.0.result.lighthouseResult.audits | server_response_time_des}}</div>
    </div>

  </a>
</article>


          <article class="post-item">
  <a class="post-item__inner" href="#">
    <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Mainthread Work Breakdown:-
          {{data.0.result.lighthouseResult.audits | mainthread_work_breakdown}}</div>
    </div>

          <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
           Mainthread Work Breakdown Details:-{{data.0.result.lighthouseResult.audits | mainthread_work_breakdown_des}}</div>
    </div>

  </a>
</article>

              <article class="post-item">
  <a class="post-item__inner" href="#">
    <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Unused Javascript:-
          {{data.0.result.lighthouseResult.audits | unused_javascript}}</div>
    </div>

          <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
           Unused Javascript Details:-{{data.0.result.lighthouseResult.audits | unused_javascript_des}}</div>
    </div>

  </a>
</article>
                  <article class="post-item">
  <a class="post-item__inner" href="#">
    <div class="post-item__content-wrapper">

              <div class="post-item__excerpt">
          Avoid an excessive DOM size:-
          {{data.0.result.lighthouseResult.audits | dom_size}}</div>
    </div>

  </a>
</article>
</section>

</body>
{% endblock %}

</html>