scrapper/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("domain.urls")),
    path("user/", include("user.urls")),
    path("", include("page_speed_insights.urls"))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
"""
    import needed things
"""
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [path("register/", views.RegistrationView.as_view(), name="register"),
               path('login/', views.LoginView.as_view(), name='login'),
               path('logout/', views.LogoutView.as_view(), name='logout'),
               ]

templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Web Crawler{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% block extrastyle %}
    {% endblock extrastyle %}
</head>
<body>
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                {% block extra_header %}

                {% endblock %}
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:register' %}">Register</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user:login' %}">Login</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
</div>

{% block extrajs %}
{% endblock %}
</body>
</html>